{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from keras.layers import Dense, Flatten\n",
    "from keras.models import Sequential\n",
    "from keras.utils import to_categorical\n",
    "from keras.datasets import mnist"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAx8AAAC0CAYAAAD1l5EVAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAA9hAAAPYQGoP6dpAAAYoUlEQVR4nO3de3DU1fnH8WeBQoIQkJuEAiaVi60IsTTEMpSABKRoEYGijFylYktNqC2USsOl2FArsVOioiJjEKEDFopcOo6iEMGSBGKEDk2RiALmMpR7EoSkJPv74zfl9/vuc0y2y+75ZrPv14x/nA9nd5/SA8nD5tnj8Xq9XgEAAACAEGvmdgEAAAAAIgPNBwAAAAAraD4AAAAAWEHzAQAAAMAKmg8AAAAAVtB8AAAAALCC5gMAAACAFTQfAAAAAKyg+QAAAABgBc0HAAAAACtoPgKUk5MjHo/H+F9eXp7b5SECVFdXy4IFC6Rbt24SHR0tSUlJsmvXLrfLQoTKyMgQj8cj/fr1c7sURICqqipZsmSJjB49Wjp06CAej0fWrl3rdlmIIB999JGMHj1aYmJipG3btjJq1Cg5dOiQ22WFhRZuFxDu0tLSJDEx0ZH16tXLpWoQSWbMmCGbN2+Wn/3sZ9K7d29Zu3atjBkzRvbs2SNDhgxxuzxEkJKSElm+fLncdNNNbpeCCHH27FlZtmyZ9OzZUwYMGCA5OTlul4QIUlhYKEOGDJEePXrIkiVLpK6uTlatWiXJycly4MAB6du3r9slNmoer9frdbuIcJSTkyPDhw+XP//5zzJx4kS3y0GEOXDggCQlJcmKFStk3rx5IiJy9epV6devn3Tp0kX279/vcoWIJA8//LCcOXNGamtr5ezZs3LkyBG3S0ITV11dLRcuXJCuXbtKQUGBJCYmSnZ2tsyYMcPt0hAB7rvvPsnNzZXi4mLp2LGjiIiUl5dLnz59ZNSoUbJlyxaXK2zc+LGrIKisrJRr1665XQYiyObNm6V58+Yye/bs61lUVJTMmjVLcnNz5YsvvnCxOkSSvXv3yubNm+WPf/yj26UggrRq1Uq6du3qdhmIUPv27ZOUlJTrjYeISGxsrCQnJ8vOnTulqqrKxeoaP5qPGzRz5kyJiYmRqKgoGT58uBQUFLhdEiLAxx9/LH369JGYmBhHPmjQIBERfu4UVtTW1kpqaqr86Ec/kjvvvNPtcgDAiurqaomOjlZ569atpaamhnd/G8DMR4BatmwpEyZMkDFjxkinTp2kqKhIMjMz5Xvf+57s379f7rrrLrdLRBNWXl4usbGxKv9PVlZWZrskRKCXX35ZTp48Ke+9957bpQCANX379pW8vDypra2V5s2bi4hITU2N5Ofni4hIaWmpm+U1erzzEaDBgwfL5s2b5dFHH5WxY8fKr371K8nLyxOPxyNPPfWU2+Whibty5Yq0atVK5VFRUdd/HQilc+fOyeLFi2XRokXSuXNnt8sBAGvmzJkjx44dk1mzZklRUZEcOXJEpk2bJuXl5SLC1+CG0HwEUa9eveSBBx6QPXv2SG1trdvloAmLjo6W6upqlV+9evX6rwOhlJ6eLh06dJDU1FS3SwEAq3784x/LwoUL5U9/+pPccccdcuedd8rx48fll7/8pYiItGnTxuUKGzeajyDr0aOH1NTUyOXLl90uBU1YbGzs9X9h+f/+k3Xr1s12SYggxcXFsnr1aklLS5OysjI5ceKEnDhxQq5evSr//ve/5cSJE3L+/Hm3ywSAkMnIyJDTp0/Lvn375O9//7scPHhQ6urqRESkT58+LlfXuNF8BNlnn30mUVFRdL0IqYSEBDl27JhUVFQ48v/8vGlCQoILVSFSlJaWSl1dnaSlpUl8fPz1//Lz8+XYsWMSHx8vy5Ytc7tMAAipm2++WYYMGXL9Azfee+896d69u9x+++0uV9a4MXAeoDNnzqifcz58+LBs375dvv/970uzZvR1CJ2JEydKZmamrF69+vo9H9XV1ZKdnS1JSUnSo0cPlytEU9avXz/ZunWrytPT06WyslJWrlwpt912mwuVAYA7Nm3aJAcPHpTMzEy+B2wAlwwG6J577pHo6GgZPHiwdOnSRYqKimT16tXyta99TXJzc+Wb3/ym2yWiiZs0aZJs3bpVnnzySenVq5e8/vrrcuDAAXn//fdl6NChbpeHCDRs2DAuGYQ1L7zwgly8eFHKysrkpZdekvHjx1//pMnU1FRp166dyxWiqdq7d68sW7ZMRo0aJR07dpS8vDzJzs6WkSNHyo4dO6RFC/5tvz40HwHKysqSDRs2yKeffioVFRXSuXNnGTFihCxZskR69erldnmIAFevXpVFixbJ+vXr5cKFC9K/f395+umn5d5773W7NEQomg/YFBcXJydPnjT+2ueffy5xcXF2C0LEOH78uMyZM0cKCwulsrJS4uPjZfr06fLzn/9cWrZs6XZ5jR7NBwAAAAAr+KE0AAAAAFbQfAAAAACwguYDAAAAgBU0HwAAAACsoPkAAAAAYAXNBwAAAAArAr4Fpa6uTsrKyqRt27bi8XiCWRPClNfrlcrKSunWrVvIb/fk/MGEMwg3cf7gNltnkPMHE3/PX8DNR1lZmfTo0SPQh6MJ++KLL6R79+4hfQ3OH+rDGYSbOH9wW6jPIOcP9Wno/AXcFrdt2zbQh6KJs3E2OH+oD2cQbuL8wW2hPh+cP9SnofMRcPPB22z4KjbOBucP9eEMwk2cP7gt1OeD84f6NHQ+GDgHAAAAYAXNBwAAAAAraD4AAAAAWEHzAQAAAMAKmg8AAAAAVtB8AAAAALCC5gMAAACAFTQfAAAAAKyg+QAAAABgBc0HAAAAACtoPgAAAABYQfMBAAAAwAqaDwAAAABW0HwAAAAAsILmAwAAAIAVLdwuAEBoDBw4UGVPPPGEYz1t2jS1Z926dSp7/vnnVVZYWHgD1QEAgEjEOx8AAAAArKD5AAAAAGAFzQcAAAAAK2g+AAAAAFjBwHkDmjdvrrJ27doF/Hy+A7+tW7dWe/r27auyn/70pyrLzMx0rCdPnqz2XL16VWXPPPOMyn7zm9/oYhE2EhISVLZr1y6VxcTEONZer1ftmTp1qsrGjh2rso4dO/4XFQLBN2LECMd6w4YNak9ycrLKPvnkk5DVhPCXnp6uMtPXyGbNnP9+O2zYMLXngw8+CFpdQFPBOx8AAAAArKD5AAAAAGAFzQcAAAAAK2g+AAAAAFjRJAfOe/bsqbKWLVuqbPDgwSobMmSIY92+fXu1Z8KECYEX54eSkhKVZWVlqezBBx90rCsrK9Wew4cPq4wBuPA2aNAglW3ZskVlpg9G8B0wN52ZmpoalZmGy++++27H2nTjuem5YDZ06FCVmX7ft27daqOcsJCYmOhYHzx40KVKEK5mzJihsgULFqisrq6uwecyfYAHAI13PgAAAABYQfMBAAAAwAqaDwAAAABWhP3Mh+lytd27d6vsRi4GDCXTz5GaLjiqqqpSme+FWuXl5WrPhQsXVMYFW42X76WT3/72t9We9evXqyw2Njag1ysuLlbZs88+q7KNGzeq7G9/+5tjbTq3v/vd7wKqKxKZLijr3bu3yiJ15sP3QjcRkfj4eMf61ltvVXs8Hk/IakL4M52ZqKgoFypBY5SUlKSyKVOmqMx0mekdd9zR4PPPmzdPZWVlZSrznUcW0d8L5OfnN/h6jQXvfAAAAACwguYDAAAAgBU0HwAAAACsoPkAAAAAYEXYD5yfOnVKZefOnVNZqAfOTYM+Fy9eVNnw4cMda9MlbG+88UbQ6kJ4eeWVVxzryZMnh/T1TAPtbdq0UZnpYkrfAen+/fsHra5ING3aNJXl5ua6UEnjZPpQhccee8yxNn0Yw9GjR0NWE8JPSkqKY52amurX40zn6P7773esT58+HXhhaBQeeughx3rlypVqT6dOnVRm+mCLnJwclXXu3NmxXrFihV91mZ7f97kefvhhv56rMeCdDwAAAABW0HwAAAAAsILmAwAAAIAVNB8AAAAArAj7gfPz58+rbP78+SrzHQwTEfn4449VlpWV1eBrHjp0SGUjR45U2eXLl1Xme+Pl3LlzG3w9NE0DBw5U2X333edY+3s7s2kgfMeOHSrLzMx0rE03qZr+XFy4cEFl99xzj2PNTdI3xnSDN/7PmjVrGtxTXFxsoRKEC9Ot0NnZ2Y61vx9GYxoMPnnyZGCFwboWLfS3u9/5zndU9uqrrzrWrVu3Vnv27t2rsqefflplH374ocpatWrlWL/55ptqz6hRo1RmUlBQ4Ne+xoivdgAAAACsoPkAAAAAYAXNBwAAAAAraD4AAAAAWBH2A+cmb731lsp2796tssrKSpUNGDDAsZ41a5ba4zu0K2IeLjf5xz/+4VjPnj3br8chvCUkJKhs165dKouJiXGsvV6v2vP222+rzHQTenJyssrS09Mda9MQ75kzZ1R2+PBhldXV1TnWvsPyIuYb1AsLC1UWaUy3wd9yyy0uVBI+/BkMNv2ZQuSaPn26yrp169bg40w3U69bty4YJcElU6ZMUZk/H2Jh+jvF9xZ0EZGKigq/6vB9rL/D5SUlJSp7/fXX/XpsY8Q7HwAAAACsoPkAAAAAYAXNBwAAAAAraD4AAAAAWNEkB85N/B0GunTpUoN7HnvsMZVt2rRJZb4DuYgMffr0Udn8+fNVZhqgPXv2rGNdXl6u9piGzKqqqlT217/+1a8sWKKjo1X2i1/8QmWPPPJIyGoIF2PGjFGZ6fcvUpmG7+Pj4xt8XGlpaSjKQRjo1KmTyh599FGV+X5dvnjxotrz29/+Nmh1wT7TbeMLFy5UmekDXVatWuVY+35Ii4j/30+a/PrXvw7ocWlpaSozfThMuOCdDwAAAABW0HwAAAAAsILmAwAAAIAVETPz4a+lS5c61gMHDlR7TJe3paSkqOzdd98NWl1onFq1aqUy0yWUpp/xN11yOW3aNMe6oKBA7Qmn2YCePXu6XUKj1LdvX7/2+V5KGilMf4ZMcyDHjh1zrE1/ptD0xMXFqWzLli0BPdfzzz+vsj179gT0XLBv8eLFKjPNd9TU1KjsnXfeUdmCBQsc6ytXrvhVR1RUlMpMFwj6fk30eDxqj2nmaNu2bX7VES545wMAAACAFTQfAAAAAKyg+QAAAABgBc0HAAAAACsYOPdx+fJlx9p0oWBhYaHKXn31VZWZhtZ8B4hffPFFtcd08Q0ap7vuuktlpuFykwceeEBlH3zwwQ3XhKbj4MGDbpdwQ2JiYlQ2evRox3rKlClqj2lQ08T3MjHThXFoenzPkIhI//79/Xrs+++/71ivXLkyKDXBjvbt2zvWc+bMUXtM30OZhsvHjRsXUA29evVS2YYNG1Rm+sAiX5s3b1bZs88+G1Bd4YR3PgAAAABYQfMBAAAAwAqaDwAAAABW0HwAAAAAsIKB8wYcP35cZTNmzFBZdna2yqZOndpgdtNNN6k969atU1l5eXl9ZcIlf/jDH1RmurHUNEge7sPlzZo5/+2irq7OpUqarg4dOgTtuQYMGKAy01lNSUlxrLt37672tGzZUmWPPPKIynzPiIi+MTg/P1/tqa6uVlmLFvrL1UcffaQyNC2moeBnnnnGr8d++OGHKps+fbpjfenSpYDqgjt8/+7p1KmTX49LS0tTWZcuXVQ2c+ZMx3rs2LFqT79+/VTWpk0blZkG332z9evXqz2+H3zUFPHOBwAAAAAraD4AAAAAWEHzAQAAAMAKmg8AAAAAVjBwHoCtW7eqrLi4WGWmYeQRI0Y41suXL1d7br31VpVlZGSorLS0tN46EXz333+/Y52QkKD2mIbMtm/fHqqSXOM7YG76333o0CFL1YQX36FrEfPv38svv6yyhQsXBvSaphugTQPn165dc6y//PJLtaeoqEhlr732msoKCgpU5vtBC6dPn1Z7SkpKVBYdHa2yo0ePqgzhLS4uzrHesmVLwM/12Wefqcx03hA+ampqHOszZ86oPZ07d1bZ559/rjLT37n+KCsrU1lFRYXKYmNjVXb27FnHeseOHQHVEO545wMAAACAFTQfAAAAAKyg+QAAAABgBc0HAAAAACsYOA+SI0eOqGzSpEkq+8EPfuBYm25Gf/zxx1XWu3dvlY0cOfK/KRFB4Dv0arrp+V//+pfKNm3aFLKagq1Vq1YqW7p0aYOP2717t8qeeuqpYJTU5MyZM0dlJ0+eVNngwYOD9pqnTp1S2VtvvaWyf/7zn451Xl5e0GowmT17tspMA6Om4WE0PQsWLHCsfT/Y4r/h703oCB8XL150rMeNG6f27Ny5U2UdOnRQ2fHjx1W2bds2x3rt2rVqz/nz51W2ceNGlZkGzk37IhHvfAAAAACwguYDAAAAgBU0HwAAAACsYOYjhHx/NlFE5I033nCs16xZo/a0aKH/bxk6dKjKhg0b5ljn5OT8V/UhNKqrq1VWXl7uQiUNM813pKenq2z+/Pkq870I7rnnnlN7qqqqbqC6yPL73//e7RJc4Xvx6le5kcvm0DiZLmkdNWpUQM/l+7P6IiKffPJJQM+F8JGfn68y08xYMJm+H0tOTlaZaV6J2bX/xTsfAAAAAKyg+QAAAABgBc0HAAAAACtoPgAAAABYwcB5kPTv319lEydOVFliYqJjbRouNykqKlLZ3r17/awONm3fvt3tEr6S74CnaZD8oYceUplpmHPChAlBqwtoyNatW90uAUH27rvvquzmm29u8HGmiy9nzJgRjJKABvleNixiHi73er0q45LB/8U7HwAAAACsoPkAAAAAYAXNBwAAAAAraD4AAAAAWMHAeQP69u2rsieeeEJl48ePV1nXrl0Des3a2lqVmW7INg04IbQ8Hk+9axGRcePGqWzu3LmhKukrPfnkkypbtGiRY92uXTu1Z8OGDSqbNm1a8AoDABHp2LGjyvz5urZq1SqVVVVVBaUmoCHvvPOO2yWEPd75AAAAAGAFzQcAAAAAK2g+AAAAAFhB8wEAAADAiogeODcNhE+ePNmxNg2Xx8XFBa2GgoIClWVkZKisMd+aHUl8byw13WBqOldZWVkqe+2111R27tw5x/ruu+9We6ZOnaqyAQMGqKx79+4qO3XqlGNtGpwzDXMCNpk+yKFPnz4qM910jcYpOztbZc2aBfbvn/v377/RcoCA3XvvvW6XEPZ45wMAAACAFTQfAAAAAKyg+QAAAABgRZOc+bjllltU9q1vfUtlL7zwgspuv/32oNWRn5+vshUrVjjW27ZtU3u4PDC8NW/eXGVz5sxR2YQJE1RWUVHhWPfu3TvgOkw/F71nzx7HevHixQE/PxAqplmqQOcDYF9CQoLKUlJSVGb6WldTU+NYv/jii2rP6dOnAy8OuEHf+MY33C4h7PG3OQAAAAAraD4AAAAAWEHzAQAAAMAKmg8AAAAAVoTdwHmHDh0c61deeUXtMQ27BXNAyDTI+9xzz6nMdIHblStXglYH7MvNzXWsDx48qPYkJib69VymywhNH5bgy/ciQhGRjRs3qmzu3Ll+1QGEg+9+97sqW7t2rf1C0KD27durzPT3nUlpaaljPW/evGCUBATNvn37VGb6QAw+POir8c4HAAAAACtoPgAAAABYQfMBAAAAwAqaDwAAAABWNJqB86SkJJXNnz9fZYMGDXKsv/71rwe1ji+//NKxzsrKUnuWL1+ussuXLwe1DjROJSUljvX48ePVnscff1xl6enpAb3eypUrVfbSSy+p7NNPPw3o+YHGyOPxuF0CABgdOXJEZcXFxSozfdDRbbfd5lifOXMmeIWFEd75AAAAAGAFzQcAAAAAK2g+AAAAAFhB8wEAAADAikYzcP7ggw/6lfmjqKhIZTt37lTZtWvXVOZ7U/nFixcDqgGRoby8XGVLly71KwMg8vbbb6vshz/8oQuVIFiOHj2qsv3796tsyJAhNsoBQs70QURr1qxRWUZGhmOdmpqq9pi+h21qeOcDAAAAgBU0HwAAAACsoPkAAAAAYAXNBwAAAAArPF6v1xvIAysqKqRdu3bBrgdNwKVLlyQmJiakr8H5Q304g3AT5w9uC/UZ5Pw5mX6v33zzTZWlpKQ41n/5y1/UnpkzZ6rs8uXLN1CdfQ2dP975AAAAAGAFzQcAAAAAK2g+AAAAAFjRaC4ZBAAAAMJNRUWFyiZNmqQy30sGf/KTn6g9pkuJm9rFg7zzAQAAAMAKmg8AAAAAVtB8AAAAALCC5gMAAACAFQycAwAAAEFkGkJPTU2tdx0peOcDAAAAgBU0HwAAAACsoPkAAAAAYEXAzYfX6w1mHWhCbJwNzh/qwxmEmzh/cFuozwfnD/Vp6HwE3HxUVlYG+lA0cTbOBucP9eEMwk2cP7gt1OeD84f6NHQ+PN4A29e6ujopKyuTtm3bisfjCag4NC1er1cqKyulW7du0qxZaH+ij/MHE84g3MT5g9tsnUHOH0z8PX8BNx8AAAAA8N9g4BwAAACAFTQfAAAAAKyg+QAAAABgBc0HAAAAACtoPgAAAABYQfMBAAAAwAqaDwAAAABW0HwAAAAAsILmAwAAAIAVNB8AAAAArKD5AAAAAGAFzQcAAAAAK/4Hw7XsQddwNkIAAAAASUVORK5CYII=",
      "text/plain": [
       "<Figure size 1000x400 with 5 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Load MNIST handwritten digit data\n",
    "(X_train, y_train), (X_test, y_test) = mnist.load_data()\n",
    "\n",
    "# Display some images\n",
    "fig, axes = plt.subplots(ncols=5, sharex=False,\n",
    "\t\t\t sharey=True, figsize=(10, 4))\n",
    "for i in range(5):\n",
    "\taxes[i].set_title(y_train[i])\n",
    "\taxes[i].imshow(X_train[i], cmap='gray')\n",
    "\taxes[i].get_xaxis().set_visible(False)\n",
    "\taxes[i].get_yaxis().set_visible(False)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Convert y_train into one-hot format \n",
    "temp = []\n",
    "for i in range(len(y_train)):\n",
    "    temp.append(to_categorical(y_train[i], num_classes=10))\n",
    "    \n",
    "y_train = np.array(temp)\n",
    "\n",
    "# Convert y_test into one-hot format \n",
    "temp = []\n",
    "for i in range(len(y_test)):\n",
    "    temp.append(to_categorical(y_test[i], num_classes=10))\n",
    "y_test = np.array(temp)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"sequential_1\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " flatten_1 (Flatten)         (None, 784)               0         \n",
      "                                                                 \n",
      " dense_2 (Dense)             (None, 10)                7850      \n",
      "                                                                 \n",
      " dense_3 (Dense)             (None, 10)                110       \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 7,960\n",
      "Trainable params: 7,960\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "model = Sequential()\n",
    "model.add(Flatten(input_shape=(28,28)))\n",
    "model.add(Dense(10, activation='sigmoid'))\n",
    "model.add(Dense(10, activation='softmax'))\n",
    "\n",
    "model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/5\n",
      "1875/1875 [==============================] - 2s 857us/step - loss: 0.5344 - acc: 0.8397 - val_loss: 0.4929 - val_acc: 0.8632\n",
      "Epoch 2/5\n",
      "1875/1875 [==============================] - 2s 811us/step - loss: 0.5209 - acc: 0.8451 - val_loss: 0.5255 - val_acc: 0.8483\n",
      "Epoch 3/5\n",
      "1875/1875 [==============================] - 2s 812us/step - loss: 0.5219 - acc: 0.8466 - val_loss: 0.5145 - val_acc: 0.8527\n",
      "Epoch 4/5\n",
      "1875/1875 [==============================] - 2s 818us/step - loss: 0.4889 - acc: 0.8576 - val_loss: 0.4743 - val_acc: 0.8640\n",
      "Epoch 5/5\n",
      "1875/1875 [==============================] - 2s 816us/step - loss: 0.4960 - acc: 0.8537 - val_loss: 0.4792 - val_acc: 0.8565\n",
      "313/313 [==============================] - 0s 492us/step\n"
     ]
    }
   ],
   "source": [
    "model.compile(loss='categorical_crossentropy', \n",
    "\t      optimizer='adam',\n",
    "\t      metrics=['acc'])\n",
    "\n",
    "# Train the Neural Network model\n",
    "model.fit(X_train, y_train, epochs=5, validation_data=(X_test,y_test))\n",
    "\n",
    "predictions = model.predict(X_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node 'categorical_crossentropy/mul' defined at (most recent call last):\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\traitlets\\config\\application.py\", line 976, in launch_instance\n      app.start()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n      self.io_loop.start()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n      self.asyncio_loop.run_forever()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n      self._run_once()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n      handle._run()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n      await self.process_one()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n      await dispatch(*args)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n      await result\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n      reply_content = await reply_content\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n      res = shell.run_cell(\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2881, in run_cell\n      result = self._run_cell(\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2936, in _run_cell\n      return runner(coro)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3135, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3338, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_19908\\3631765273.py\", line 1, in <cell line: 1>\n      score = model.evaluate(X_test, y_test, verbose = 0)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\training.py\", line 1947, in evaluate\n      tmp_logs = self.test_function(iterator)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\training.py\", line 1727, in test_function\n      return step_function(self, iterator)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\training.py\", line 1713, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\training.py\", line 1701, in run_step\n      outputs = model.test_step(data)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\training.py\", line 1667, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\training.py\", line 1052, in compute_loss\n      return self.compiled_loss(\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\losses.py\", line 272, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\losses.py\", line 1990, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\backend.py\", line 5544, in categorical_crossentropy\n      return -tf.reduce_sum(target * tf.math.log(output), axis)\nNode: 'categorical_crossentropy/mul'\nIncompatible shapes: [32,10] vs. [32,10,10,10,10]\n\t [[{{node categorical_crossentropy/mul}}]] [Op:__inference_test_function_94311]",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32md:\\Code\\Personal projects\\ML-Lab\\Digit-Recog.ipynb Cell 6\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[1;34m()\u001b[0m\n\u001b[1;32m----> <a href='vscode-notebook-cell:/d%3A/Code/Personal%20projects/ML-Lab/Digit-Recog.ipynb#W5sZmlsZQ%3D%3D?line=0'>1</a>\u001b[0m score \u001b[39m=\u001b[39m model\u001b[39m.\u001b[39;49mevaluate(X_test, y_test, verbose \u001b[39m=\u001b[39;49m \u001b[39m0\u001b[39;49m) \n\u001b[0;32m      <a href='vscode-notebook-cell:/d%3A/Code/Personal%20projects/ML-Lab/Digit-Recog.ipynb#W5sZmlsZQ%3D%3D?line=2'>3</a>\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m'\u001b[39m\u001b[39mTest loss:\u001b[39m\u001b[39m'\u001b[39m, score[\u001b[39m0\u001b[39m]) \n\u001b[0;32m      <a href='vscode-notebook-cell:/d%3A/Code/Personal%20projects/ML-Lab/Digit-Recog.ipynb#W5sZmlsZQ%3D%3D?line=3'>4</a>\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m'\u001b[39m\u001b[39mTest accuracy:\u001b[39m\u001b[39m'\u001b[39m, score[\u001b[39m1\u001b[39m])\n",
      "File \u001b[1;32mc:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\utils\\traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     67\u001b[0m     filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[0;32m     68\u001b[0m     \u001b[39m# To get the full stack trace, call:\u001b[39;00m\n\u001b[0;32m     69\u001b[0m     \u001b[39m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[1;32m---> 70\u001b[0m     \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39m\n\u001b[0;32m     71\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m     72\u001b[0m     \u001b[39mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[1;32mc:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py:54\u001b[0m, in \u001b[0;36mquick_execute\u001b[1;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[0;32m     52\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m     53\u001b[0m   ctx\u001b[39m.\u001b[39mensure_initialized()\n\u001b[1;32m---> 54\u001b[0m   tensors \u001b[39m=\u001b[39m pywrap_tfe\u001b[39m.\u001b[39mTFE_Py_Execute(ctx\u001b[39m.\u001b[39m_handle, device_name, op_name,\n\u001b[0;32m     55\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[0;32m     56\u001b[0m \u001b[39mexcept\u001b[39;00m core\u001b[39m.\u001b[39m_NotOkStatusException \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m     57\u001b[0m   \u001b[39mif\u001b[39;00m name \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n",
      "\u001b[1;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node 'categorical_crossentropy/mul' defined at (most recent call last):\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\traitlets\\config\\application.py\", line 976, in launch_instance\n      app.start()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n      self.io_loop.start()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n      self.asyncio_loop.run_forever()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n      self._run_once()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n      handle._run()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n      await self.process_one()\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n      await dispatch(*args)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n      await result\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n      reply_content = await reply_content\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n      res = shell.run_cell(\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2881, in run_cell\n      result = self._run_cell(\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2936, in _run_cell\n      return runner(coro)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3135, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3338, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_19908\\3631765273.py\", line 1, in <cell line: 1>\n      score = model.evaluate(X_test, y_test, verbose = 0)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\training.py\", line 1947, in evaluate\n      tmp_logs = self.test_function(iterator)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\training.py\", line 1727, in test_function\n      return step_function(self, iterator)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\training.py\", line 1713, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\training.py\", line 1701, in run_step\n      outputs = model.test_step(data)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\training.py\", line 1667, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\training.py\", line 1052, in compute_loss\n      return self.compiled_loss(\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\engine\\compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\losses.py\", line 272, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\losses.py\", line 1990, in categorical_crossentropy\n      return backend.categorical_crossentropy(\n    File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\keras\\backend.py\", line 5544, in categorical_crossentropy\n      return -tf.reduce_sum(target * tf.math.log(output), axis)\nNode: 'categorical_crossentropy/mul'\nIncompatible shapes: [32,10] vs. [32,10,10,10,10]\n\t [[{{node categorical_crossentropy/mul}}]] [Op:__inference_test_function_94311]"
     ]
    }
   ],
   "source": [
    "score = model.evaluate(X_test, y_test, verbose = 0) \n",
    "\n",
    "print('Test loss:', score[0]) \n",
    "print('Test accuracy:', score[1])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
